### ISSUE TITLE
Add keyring to dev environment

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/jupyterlab-starters#15]
## Description

`twine upload` presently failing... looks like it just needs `keyring>=15.1`. Investigate upstream.

## Reproduce

`twine upload dist/*`

```
Traceback (most recent call last):
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/bin/twine", line 10, in <module>
    sys.exit(main())
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/lib/python3.7/site-packages/twine/__main__.py", line 25, in main
    return dispatch(sys.argv[1:])
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/lib/python3.7/site-packages/twine/cli.py", line 72, in dispatch
    main = registered_commands[args.command].load()
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "~/projects/deathbeds/jupyterlab-starters/envs/default/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'keyring>=15.1' distribution was not found and is required by the application
```

## Expected behavior

Uploads to twine

**Comment by bollwyvl** [comment]
Opened upstream (midstream?) PR: https://github.com/conda-forge/twine-feedstock/pull/29

**Comment by bollwyvl** [comment]
Resolved by upstream PR
